# ──────────────────────────────────────────────
# Cloud Build — CI/CD Pipeline
# ──────────────────────────────────────────────
# Triggered on push to main branch.
# Builds both Docker images and deploys them to Cloud Run.

substitutions:
  _REGION: us-central1
  _PROJECT_ID: ${PROJECT_ID}
  _REPO: rag-repo
  _INGESTOR_SERVICE: rag-ingestor
  _AGENT_SERVICE: rag-agent
  _INGESTOR_SA: rag-ingestor-sa@${PROJECT_ID}.iam.gserviceaccount.com
  _AGENT_SA: rag-api-agent-sa@${PROJECT_ID}.iam.gserviceaccount.com
  _VPC_CONNECTOR: projects/${PROJECT_ID}/locations/${_REGION}/connectors/rag-vpc-connector

steps:
  # ────────── Build Ingestor Image ──────────
  - id: "build-ingestor"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_INGESTOR_SERVICE}:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_INGESTOR_SERVICE}:latest"
      - "./ingestion"

  # ────────── Build Agent Image ──────────
  - id: "build-agent"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_AGENT_SERVICE}:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_AGENT_SERVICE}:latest"
      - "./app"

  # ────────── Push Ingestor Image ──────────
  - id: "push-ingestor"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_INGESTOR_SERVICE}"
    waitFor: ["build-ingestor"]

  # ────────── Push Agent Image ──────────
  - id: "push-agent"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_AGENT_SERVICE}"
    waitFor: ["build-agent"]

  # ────────── Deploy Ingestor to Cloud Run ──────────
  - id: "deploy-ingestor"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_INGESTOR_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_INGESTOR_SERVICE}:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--service-account=${_INGESTOR_SA}"
      - "--set-env-vars=PROJECT_ID=${_PROJECT_ID}"
      - "--min-instances=0"
      - "--max-instances=3"
      - "--memory=512Mi"
      - "--timeout=300"
      - "--no-allow-unauthenticated"
      - "--vpc-connector=${_VPC_CONNECTOR}"
      - "--vpc-egress=all-traffic"
    waitFor: ["push-ingestor"]

  # ────────── Deploy Agent API to Cloud Run ──────────
  - id: "deploy-agent"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_AGENT_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_AGENT_SERVICE}:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--service-account=${_AGENT_SA}"
      - "--set-env-vars=PROJECT_ID=${_PROJECT_ID}"
      - "--min-instances=0"
      - "--max-instances=5"
      - "--memory=512Mi"
      - "--timeout=60"
      - "--allow-unauthenticated"
      - "--vpc-connector=${_VPC_CONNECTOR}"
      - "--vpc-egress=all-traffic"
    waitFor: ["push-agent"]

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_INGESTOR_SERVICE}:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_INGESTOR_SERVICE}:latest"
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_AGENT_SERVICE}:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_AGENT_SERVICE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
